export const metadata = {
	title: 'Check out | Another E Commerce Site',
	description: 'Generated by create next app'
}

export default function CheckoutLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<section className='mt-4 sm:mt-6 2xl:mt-8 border border-neutral-200 dark:border-neutral-700 rounded-md'>
			{children}
		</section>
	)
}
