import './globals.css'

import QueryWrapper from './queryWrapper'

import Topbar from './topbar'

import { Providers } from './providers'

export const metadata = {
	title: 'Another E Commerce Site',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className='bg-neutral-100 dark:bg-neutral-900 h-screen w-screen min-w-[300px] flex flex-col px-4 sm:px-6 2xl:px-8 overflow-hidden'>
				<QueryWrapper>
					<Providers>
						<Topbar />
						{children}
					</Providers>
				</QueryWrapper>
			</body>
		</html>
	)
}
