import './globals.css'

import QueryWrapper from './queryWrapper'

import Topbar from './topbar'
import Footer from './footer'

import { Providers } from './providers'

export const metadata = {
	title: 'Another E Commerce Site',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en' suppressHydrationWarning>
			<body className='bg-neutral-100 dark:bg-neutral-900 min-w-[300px] flex flex-col overflow-y-auto'>
				<QueryWrapper>
					<Providers>
						<div className='flex flex-col p-4 sm:p-6 2xl:p-8'>
							<Topbar />
							{children}
						</div>
						<Footer />
					</Providers>
				</QueryWrapper>
			</body>
		</html>
	)
}
