import './globals.css'

import Wrapper from './wrapper'

import Header from './header'
import Footer from './footer'

export const metadata = {
	title: 'Another E Commerce Site',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children,
	modal
}: {
	children: React.ReactNode
	modal: React.ReactNode
}) {
	const content = (
		<>
			<div className='flex flex-col'>
				<div className='min-h-screen flex flex-col p-4 sm:p-6 2xl:p-8'>
					<Header />
					{children}
				</div>
				<Footer />
			</div>
			{modal}
		</>
	)

	return (
		<html lang='en' suppressHydrationWarning>
			<body className='bg-neutral-100 dark:bg-neutral-900 flex flex-col overflow-y-auto'>
				<Wrapper content={content} />
			</body>
		</html>
	)
}
