import ProductPage from '@/app/product/[title]/productPage'

export const metadata = {
	title: 'Product | Another E Commerce Site',
	description: 'Generated by create next app'
}

export default function Product() {
	return (
		<main className='h-full w-full flex justify-center items-center border border-neutral-200 dark:border-neutral-700 rounded-md'>
			<div className='py-4 sm:py-6 2xl:py-8'>
				<ProductPage />
			</div>
		</main>
	)
}
