import ProductPage from '@/app/product/[productId]/productPage'

export const metadata = {
	title: 'Product | Another E Commerce Site',
	description: 'Generated by create next app'
}

export default function Product() {
	return (
		<main className='flex justify-center border border-neutral-200 dark:border-neutral-700'>
			<div className='w-3/4'>
				<ProductPage />
			</div>
		</main>
	)
}
